var router = require("express").Router();

const { Checkout } = require("checkout-sdk-node");
const dotenv = require("dotenv");
const cko = new Checkout(process.env.SECRET_KEY, {
  pk: process.env.PUBLIC_KEY,
});

router.post("/payments", async (req, res) => {
  // The token generated by Frames on the front end
  const myToken = req.body.token;

  const paymentResponse = await cko.payments.request({
    source: {
      token: myToken,
    },
    amount: 20000,
    currency: "HKD",
    processing_channel_id: process.env.PROCESSING_CHANNEL,
    risk: {
      enabled: false,
    },
  });

  res.send(paymentResponse);
});

module.exports = router;
